#include <cairo.h> 
#include <cairo-pdf.h> 
int main(void){ 
	cairo_surface_t *surface; 
	cairo_t *cr; 
	cairo_surface_t* pdf_surface = cairo_pdf_surface_create("dessin.pdf",100,100); 
	cr = cairo_create(pdf_surface);
	cairo_move_to(cr,0, 10) ;
	cairo_line_to(cr,10, 10);
	cairo_set_line_width(cr, 1.0);
	cairo_line_to(cr,10, 0);
	cairo_set_line_width(cr, 1.0);
	cairo_line_to(cr,50, 10);
	cairo_set_line_width(cr, 1.0);
	cairo_move_to(cr,50, 50) ;
	cairo_line_to(cr,50, 60);
	cairo_set_line_width(cr, 1.0);
	cairo_line_to(cr,60, 60);
	cairo_set_line_width(cr, 1.0);
	cairo_line_to(cr,60, 50);
	cairo_set_line_width(cr, 1.0);
	cairo_line_to(cr,50, 50);
	cairo_set_line_width(cr, 1.0);
	cairo_move_to(cr,80, 75) ;
	cairo_line_to(cr,90, 90);
	cairo_set_line_width(cr, 1.0);
	cairo_line_to(cr,95, 100);
	cairo_set_line_width(cr, 1.0);
	cairo_line_to(cr,70, 70);
	cairo_set_line_width(cr, 1.0);
	cairo_move_to(cr,10, 80) ;
	cairo_line_to(cr,20, 70);
	cairo_set_line_width(cr, 1.0);
	cairo_line_to(cr,10, 60);
	cairo_set_line_width(cr, 1.0);
	cairo_line_to(cr,10, 80);
	cairo_set_line_width(cr, 1.0);
	cairo_line_to(cr,0, 100);
	cairo_set_line_width(cr, 1.0);
	cairo_line_to(cr,20, 100);
	cairo_set_line_width(cr, 1.0);
	cairo_line_to(cr,10, 80);
	cairo_set_line_width(cr, 1.0);
	cairo_line_to(cr,30, 80);
	cairo_set_line_width(cr, 1.0);
	cairo_stroke(cr);
	cairo_destroy(cr);
	cairo_surface_destroy(pdf_surface);
	return 0;
}